name: MoneyGeek Insurance Flow Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run tests daily at 9 AM UTC to monitor site functionality
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
      
    - name: Run MoneyGeek Insurance Flow Test
      run: npx playwright test home-insurance-flow.spec.ts --headed=false
      env:
        # Set environment variables if needed
        PWDEBUG: 0
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Upload screenshots on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots
        path: test-results/
        retention-days: 7